[package]
name = "pc-types"
version = "0.1.1"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
pc-crypto = { path = "../pc-crypto" }
pc-codec = { path = "../pc-codec" }

[dev-dependencies]
proptest = "1.5"
