[package]
name = "pc-types-fuzz"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false

[dependencies]
libfuzzer-sys = "0.4"
pc-types = { path = ".." }
pc-codec = { path = "../../pc-codec" }

[workspace]

[[bin]]
name = "types_anchor_header_v2"
path = "fuzz_targets/types_anchor_header_v2.rs"
test = false
bench = false

[[bin]]
name = "types_anchor_payload_v2"
path = "fuzz_targets/types_anchor_payload_v2.rs"
test = false
bench = false

[[bin]]
name = "types_evidence_event"
path = "fuzz_targets/types_evidence_event.rs"
test = false
bench = false

[package.metadata]
cargo-fuzz = true
