[package]
name = "pc-state"
version = "0.0.1"
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
pc-types = { path = "../pc-types" }
pc-crypto = { path = "../pc-crypto" }

[features]
default = []
rocksdb = ["dep:rocksdb"]

[dependencies.rocksdb]
version = "0.21"
optional = true
