global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts/phantom-node-alerts.yaml

scrape_configs:
  - job_name: 'phantom-node'
    static_configs:
      - targets: ['host.docker.internal:9100']
