name: pc-p2p nightly benches

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  benches-nightly:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: pc-p2p-benches-nightly

      - name: Cargo check
        run: cargo check --locked

      - name: Bench libp2p RPC (nightly)
        run: cargo bench -p pc-p2p --features "async libp2p" --bench p2p_libp2p_rpc -- --measurement-time 20 --sample-size 10

      - name: Bench libp2p E2E (nightly)
        run: cargo bench -p pc-p2p --features "async libp2p" --bench p2p_libp2p_e2e -- --measurement-time 20 --sample-size 10

      - name: Bench QUIC (nightly)
        run: cargo bench -p pc-p2p --features "async quic" --bench p2p_quic_bench -- --measurement-time 20 --sample-size 10

      - name: Aggregation
        run: cargo run -p pc-p2p --bin bench_agg

      - name: Regression Gate vs Baseline
        env:
          BENCH_P50_TOL: '0.10'
          BENCH_P95_TOL: '0.10'
          BENCH_TIMEOUT_TOL: '0.02'
        run: cargo run -p pc-p2p --bin bench_gate -- --agg target/criterion_agg.csv

      - name: Upload Aggregation
        uses: actions/upload-artifact@v4
        with:
          name: criterion-agg-nightly
          path: |
            target/criterion_agg.json
            target/criterion_agg.csv
            target/criterion_agg.md

      - name: Upload Raw
        uses: actions/upload-artifact@v4
        with:
          name: criterion-raw-nightly
          path: target/criterion_raw
